### PR TITLE
v2.2.0

### PR DESCRIPTION
**Pull request by padurets**
it is now possible to set prefixes and suffixes for indexes. Leads to the mind:
```js
const keys = require('all-object-keys');

var options = {
    iPrefix: '[',
    iSuffix: ']'
};

var obj =  {
    universal: true,
    hello: {
        world: {
            x: 'could be used in browser as well'
        }
    },
    array: ['a','b', {c: 'e'}]
};

keys(options, obj)
// returns
// ["universal", "hello.world.x", "array[0]", "array[1]", "array[2].c"]

keys(obj)
// returns
// ["universal", "hello.world.x", "array.0", "array.1", "array.2.c"]
```

### CODE REVIEW

**Comment by coderaiser** [comment]
Why you need this feature?

**Comment by padurets** [comment]
to format [lodash.get](https://lodash.com/docs/4.17.2#get)

```js
var lodashGet = require('lodash.get');
var object = { 'a': [{ 'b': { 'c': 3 } }] };
 
lodashGet(object, 'a[0].b.c');
// => 3
```

**Comment by coderaiser** [comment]
You can do the same things using [jessy](https://github.com/coderaiser/jessy "jessy") already:

```js
const obj =  {
    array: ['a','b', {c: 'e'}]
};

const keys = allObjectKeys(obj);
// returns
["array.0", "array.1", "array.2.c"]

jessy('array.2.c', obj);
// returns
"e"
```

**Comment by padurets** [comment]
in another package used lodash, I need the functionality of your module with the ability to change the prefixes. So I decided to pull request, instead of doing a separate package. Do you think is better to make this functionality requirements, based on a new package?

**Comment by coderaiser** [comment]
Yes, I think you better fork `all-object-keys` to make something that will fit your needs more.

**Pull request closed without merging**
